chap_vocab = {"nothing": "there",
              "hello": "goodbye"}
import random, os
def get_definition():
    os.system('cls' if os.name == 'nt' else 'clear')
    glossary_dict = {
        "gender gap": "the regular pattern in which women are more likely to support Democratic candidates, in part because they tend to be less conservative than men and more likely to support spending on social services and to oppose higher levels of military spending",
        "Gibbons v. Ogden": "a landmark case decided in 1824 in which the Supreme Court interpreted very broadly the clause in Article I Section 8 of the Constitution and defined the power of Congress to regulate interstate commerce as encompassing virtually every form of commercial activity",
        "Gideon v. Wainwright": "the 1963 Supreme Court decision holding that anyone accused of a felony where imprisonment may be imposed has a right to a lawyer. The decision requires the government to provide a lawyer to anyone so accused who is too poor to afford one",
        "Gitlow v. New York": "the 1925 Supreme Court decision holding that freedoms of press and speech are fundamental personal rights and liberties protected by the due process clause of the Fourteenth Amendment from impairment by the states as well as by the federal government",
        "global warming": "the increase in the earth's temperatures that, according to most scientists, is occurring as a result of the carbon dioxide that is produced when fossil fuels are burned collecting in the atmosphere and trapping energy",
        "government": "the institutions through which public policies are made for a society",
        "government corporation": "a government organization that, like business corporations, provides a service that could be delivered by the private sector and typically charges for its services. The U.S. Postal Service is an example",
        "Gregg v. Georgia": "the 1976 Supreme Court decision that upheld the constitutionality of the death penalty, as an extreme sanction, suitable to the most extreme of crimes",
        "gross domestic product (GDP)": "the sum total of the value of all the goods and services produced in a year in a nation",
        "GS (General Schedule) rating": "a schedule for federal employees, ranging from GS 1 to GS 18, by which salaries can be keyed to rating and experience",
        "Hatch Act": "a federal law prohibiting government employees from active participation in partisan politics while on duty or for employees in sensitive positions at any time",
        "health maintenance organization": "organization contracted by individuals or insurance companies to provide health care for a yearly fee. Such network health plans limit the choice of doctors and treatments. More than half of Americans are enrolled in health maintenance organizations or similar programs",
        "Hernandez v. Texas": "a 1954 Supreme Court decision that extended protection against discrimination to Hispanics",
        "high-tech politics": "a politics in which the behavior of citizens and policymakers and the political agenda itself are increasingly shaped by technology",
        "House Ways and Means Committee": "the House of Representatives committee that, along with the Senate Finance Committee, writes the tax codes, subject to the approval of Congress as a whole",
        "hyperpluralism": "a theory of American democracy arguing that a wide variety of interest groups have become empowered with the ability to veto policy change, thereby leading to regular gridlock in Washington",
        "impeachment": "the political equivalent of an indictment in criminal law, prescribed by the Constitution. The House of Representatives may impeach the president by a majority vote for Treason, Bribery, or other high Crimes and Misdemeanors",
        "implied powers": "powers of the federal government that go beyond those enumerated in the Constitution, in accordance with the statement in the Constitution that Congress has the power to make all laws necessary and proper for carrying into execution the powers enumerated in Article 1",
        "incentive system": "an alternative to command-and-control, with market-like strategies such as rewards used to manage public policy",
        "income": "the amount of money collected between any two points in time",
        "income distribution": "the way the national income is divided into shares ranging from the poor to the rich",
        "income tax": "shares of individual wages and corporate revenues collected by the government. The Sixteenth Amendment explicitly authorized Congress to levy a tax on income",
        "incorporation doctrine": "the legal concept under which the Supreme Court has nationalized the Bill of Rights by making most of its provisions applicable to the states through the Fourteenth Amendment",
        "Incrementalism": "a description of the budget process in which the best predictor of this year's budget is last year's budget, plus a little bit more (an increment). According to Aaron Wildavsky, most of the budget is a product of previous decisions",
        "incumbents": "those individuals who already hold office. In congressional elections, incumbents usually win",
        "independent executive agency": "the government agencies not accounted for by cabinet departments. Their administrators are appointed by the president and serve at the president's pleasure. NASA is an example",
        "independent expenditures": "expenses on behalf of a political message that are made by groups that are uncoordinated with any candidate's campaign",
        "independent regulatory commission": "a government agency with responsibility for making and enforcing rules to protect the public interest in some sector of the economy and for judging disputes over these rules",
        "inflation": "a rise in price of goods and services",
        "interest group": "an organization of people with a shared policy goal, or goals, who enter the policy process at one or more points, in one or more policy arenas, to try to achieve their goals",
        "intergovernmental relations": "the entire set of interactions among national, state, and local governments—including regulations, transfers of funds, and the sharing of information—that constitute the workings of the federal system",
        "investigative journalism": "the use of in-depth reporting to unearth scandals, scams, and schemes, at times putting reporters in adversarial relationships with political leaders",
        "invisible primary": "the period before any votes are cast when candidates compete to win early support from the elite of the party and to create a positive first impression of their leadership skills",
        "iron triangles": "also known as subgovernments, consist of interest groups, government agencies, and congressional committees or subcommittees that have a mutually dependent, mutually advantageous relationship; they dominate some areas of domestic policymaking",
        "judicial activism": "an approach to decision making in which judges sometimes make bold policy decisions, even charting new constitutional ground",
        "judicial implementation": "how and whether court decisions are translated into actual policy, thereby affecting the behavior of others. The courts rely on other units of government to enforce their decisions",
        "judicial restraint": "an approach to decision making in which judges play minimal policymaking roles and defer to legislatures whenever possible",
        "judicial review": "the power of the courts to determine whether acts of Congress and those of the executive branch are in accord with the U.S. Constitution. Judicial review was established by Marbury v. Madison",
        "justiciable disputes": "issues capable of being settled as a matter of law",
        "Keynesian economic theory": "named after English economist John Maynard Keynes, the theory emphasizing that government spending and deficits can help the economy deal with its ups and downs. Proponents of this theory advocate using the power of government to stimulate the economy when it is lagging",
        "Korematsu v. United States": "a 1944 Supreme Court decision that upheld as constitutional the internment of more than 100,000 Americans of Japanese descent in encampments during World War II",
        "laissez-faire": "the principle that government should not meddle in the economy",
        "legislative oversight": "Congress's monitoring of the executive branch bureaucracy and its administration of policy, performed mainly through committee hearings",
        "legislative veto": "a vote in Congress to override a presidential decision. Although the War Powers Resolution asserts this authority, there is reason to believe that, if challenged, the Supreme Court would find the legislative veto in violation of the doctrine of separation of powers",
        "Lemon v. Kurtzman": "the 1971 Supreme Court decision that established that aid to church-related schools must (1) have a secular legislative purpose; (2) have a primary effect that neither advances nor inhibits religion; and (3) not foster excessive government entanglement with religion",
        "libel": "the publication of false and malicious statements that may damage someone's reputation",
        "limited government": "the idea that certain restrictions should be placed on government to protect the natural rights of citizens",
        "linkage institutions": "the political channels through which people's concerns become political issues on the policy agenda. In the United States, linkage institutions include elections, political parties, interest groups, and the media",
        "lobbying": "communication, by someone other than a citizen acting on his or her own behalf, directed to a governmental decision maker with the hope of influencing his or her decision",
        "majority leader": "the principal partisan ally of the Speaker of the House or the majority party's manager in the Senate. The majority leader in each house is responsible for scheduling bills, influencing committee assignments, and rounding up votes on behalf of the party's legislative positions",
        "majority rule": "a fundamental principle of traditional democratic theory. In a democracy, choosing among alternatives requires that the majority's desire be respected",
        "mandate theory of elections": "the idea that the winning candidate has a mandate from the people to carry out his or her platforms and politics. Politicians like the theory better than political scientists do",
        "Mapp v. Ohio": "the 1961 Supreme Court decision ruling that the Fourth Amendment's protection against unreasonable searches and seizures must be extended to the states",
        "Marbury v. Madison": "the 1803 case in which the Supreme Court asserted its power to determine the meaning of the U.S. Constitution. The decision established the Court's power of judicial review over acts of Congress",
        "mass media": "television, radio, newspapers, magazines, the Internet, and other means of popular communication",
        "McCleskey v. Kemp": "the 1987 Supreme Court decision that upheld the constitutionality of the death penalty against charges that it violated the Fourteenth Amendment because minority defendants were more likely to receive the death penalty than were white defendants",
        "McCulloch v. Maryland": "an 1819 Supreme Court decision that established the supremacy of the national government over state governments. The Court, led by Chief Justice John Marshall, held that Congress had certain implied powers in addition to the powers enumerated in the Constitution",
        "McGovern-Fraser Commission": "a commission formed at the 1968 Democratic convention in response to demands for reform by minority groups and others who sought better representation",
        "means-tested programs": "government programs providing benefits only to individuals who qualify based on specific needs",
        "media events": "events that are purposely staged for the media and that are significant just because the media are there",
        "Medicaid": "a public assistance program designed to provide health care for poor Americans and funded by both the states and the national government",
        "Medicare": "a program added to the Social Security system in 1965 that provides health insurance for the elderly, covering hospitalization, doctor fees, and other health expenses",
        "melting pot": "a term often used to characterize the United States, with its history of immigration and mixing of cultures, ideas, and peoples",
        "merit principle": "the idea that hiring should be based on entrance exams and promotion ratings to produce administration by people with talent and skill",
        "Miami Herald Publishing Company v. Tornillo": "a 1974 case in which the Supreme Court held that a state could not force a newspaper to print replies from candidates it had criticized. The case illustrates the limited power of government to restrict the print media",
        "Miller v. California": "a 1973 Supreme Court decision holding that community standards be used to determine whether material is obscene, defined as appealing to a prurient interest, being patently offensive, and lacking in literary, artistic, political, or scientific value",
        "minority leader": "the principal leader of the minority party in the House of Representatives or in the Senate",
        "minority majority": "the situation, likely beginning in the twenty-first century, in which the non-Hispanic whites represent a minority of the U.S. population and minority groups together will represent a majority",
        "minority rights": "a principle of traditional democratic theory that guarantees rights to those who do not belong to majorities",
        "Miranda v. Arizona": "the 1966 Supreme Court decision that set guidelines for police questioning of accused persons to protect them against self-incrimination and to protect their right to counsel",
        "monetarism": "an economic theory holding that the supply of money is the key to a nation's economic health, with too much cash and credit in circulation producing inflation",
        "monetary policy": "government manipulation of the supply of money in private hands, one of two important tools by which the government can attempt to steer the economy",
        "Motor Voter Act": "a 1993 act that requires states to permit people to register to vote when they apply for a driver's license",
        "NAACP v. Alabama": "the 1958 Supreme Court decision that the right to assemble meant that Alabama could not require the state chapter of NAACP to reveal its membership list",
        "narrowcasting": "media programming on cable TV, e.g., on MTV, ESPN, or C-SPAN, or the Internet, that is focused on a particular interest and aimed at a particular audience, in contrast to broadcasting",
        "national chairperson": "the person responsible for running the ongoing activities of the national party organization",
        "national committee": "one of the institutions that keeps the party operating between conventions. The national committee is composed of representatives from the states and territories",
        "national debt": "all the money borrowed by the federal government over the years and still outstanding. Today the national debt is about $18.7 trillion",
        "National Environmental Policy Act": "passed in 1969, the centerpiece of federal environmental policy, which requires agencies to file environmental impact statements",
        "national health insurance": "a compulsory insurance program for all Americans that would have the government finance citizens' medical care. First proposed by President Harry S. Truman",
        "national party convention": "the supreme power within each of the parties. The convention meets every four years to nominate the party's presidential and vice presidential candidates and to write the party's platform",
        "National Security Council": "the committee that links the president's foreign and military policy advisers. Its formal members are the president, vice president, secretary of state, and secretary of defense, and it is managed by the president's national security assistant",
        "natural rights": "rights inherent in human beings, not dependent on governments, which include life, liberty, and property. The concept of natural rights was central to English philosopher John Locke's theories about government and was widely accepted among America's Founders",
        "Near v. Minnesota": "the 1931 Supreme Court decision holding that the First Amendment protects newspapers from prior restraint",
        "New Deal coalition": "a coalition forged by the Democrats, who dominated American politics from the 1930s to the 1960s. Its basic elements were the urban working class, ethnic groups, Catholics and Jews, the poor, Southerners, African Americans, and intellectuals",
        "New Jersey Plan": "the proposal at the Constitutional Convention that called for equal representation of each state in Congress regardless of the size of the state's population",
        "New York Times v. Sullivan": "a 1964 Supreme Court decision establishing that, to win damage suits for libel, public figures must prove that the defamatory statements about them were made with actual malice and reckless disregard for the truth",
        "Nineteenth Amendment": "the constitutional amendment adopted in 1920 that guarantees women the right to vote",
        "nomination": "the official endorsement of a candidate for office by a political party. Generally, success in the nomination game requires momentum, money, and media attention",
        "Office of Management and Budget": "an office that prepares the president's budget and also advises presidents on proposals from departments and agencies and helps review their proposed regulations",
        "Office of Personnel Management": "the office in charge of hiring for most agencies of the federal government, using elaborate rules in the process",
        "open primaries": "elections to select party nominees in which voters can decide on Election Day whether they want to participate in the Democratic or Republican contests",
        "opinion": "a statement of legal reasoning behind a judicial decision. The content of an opinion may be as important as the decision itself",
        "original jurisdiction": "the jurisdiction of courts that hear a case first, usually in a trial. These are the courts that determine the facts about a case",
        "originalism": "a view that the Constitution should be interpreted according to the original intentions or original meaning of the Framers. Many conservatives support this view",
        "party dealignment": "the gradual disengagement of people from the parties, as seen in part by shrinking party identification",
        "party eras": "historical periods in which a majority of voters cling to the party in power, which tends to win a majority of the elections",
        "party identification": "a citizen's self-proclaimed preference for one party or the other",
        "party image": "the voter's perception of what the Republicans or Democrats stand for, such as conservatism or liberalism",
        "party machines": "a type of political party organization that relies heavily on material inducements, such as patronage, to win votes and to govern",
        "party platform": "a political party's statement of its goals and policies for the next four years. The platform is drafted prior to the party convention by a committee whose members are chosen in rough proportion to each candidate's strength. It is the best formal statement of a party's beliefs",
        "party polarization": "the growing gap between the stands of the parties on policy issues. On the negative side, polarization makes compromise more difficult, whereas on the positive side clear differences between the parties makes politics easier to understand for voters",
        "party realignment": "the displacement of the majority party by the minority party, usually during a critical election period",
        "patronage": "one of the key inducements used by party machines. A patronage job, promotion, or contract is one that is given for political reasons rather than for merit or competence alone",
        "Pendleton Civil Service Act": "passed in 1883, an act that created a federal civil service so that hiring and promotion would be based on merit rather than patronage",
        "Personal Responsibility and Work Opportunity Reconciliation Act": "the welfare reform law of 1996, which implemented the Temporary Assistance for Needy Families program",
        "Planned Parenthood v. Casey": "a 1992 case in which the Supreme Court loosened its standard for evaluating restrictions on abortion from one of strict scrutiny of any restraints on a fundamental right to abortion to one in which regulations not impose an undue burden on women",
        "plea bargaining": "a bargain struck between a defendant's lawyer and a prosecutor to the effect that the defendant will plead guilty to a lesser crime or fewer crimes in exchange for the state's promise not to prosecute the defendant for a more serious crime or for additional crimes",
        "Plessy v. Ferguson": "an 1896 Supreme Court decision that provided a constitutional justification for segregation by ruling that a Louisiana law requiring equal but separate accommodations for the white and colored races was constitutional",
        "pluralism": "a theory of American democracy emphasizing that the policymaking process is very open to the participation of all groups with shared interests, with no single group usually dominating. Pluralists tend to believe that as a result, public interest generally prevails",
        "pocket veto": "a type of veto occurring when Congress adjourns within 10 days of submitting a bill to the president and the president simply lets the bill die by neither signing nor vetoing it",
        "policy agenda": "the issues that attract the serious attention of public officials and other people involved in politics at a point in time",
        "policy entrepreneurs": "people who invest their political capital in an issue. According to John Kingdon, a policy entrepreneur could be in or out of government, in elected or appointed positions, in interest groups or research organizations",
        "policy gridlock": "a condition that occurs when interests conflict and no coalition is strong enough to form a majority and establish policy, so nothing gets done",
        "policy impacts": "the effects a policy has on people and problems. Impacts are analyzed to see how well a policy has met its goal and at what cost",
        "policy implementation": "the stage of policymaking between the establishment of a policy and the consequences of the policy for the people affected. Implementation involves translating the goals and objectives of a policy into an operating, ongoing program",
        "policymaking institutions": "the branches of government charged with taking action on political issues. The U.S. Constitution established three policymaking institutions—Congress, the presidency, and the courts. Today, the power of the bureaucracy is so great that most political scientists consider it a fourth policymaking institution",
        "policymaking system": "the process by which policy comes into being and evolves. People's interests, problems, and concerns create political issues for government policymakers. These issues shape policy, which in turn impacts people, generating more interests, problems, and concerns",
        "policy voting": "electoral choices that are made on the basis of the voters' policy preferences and where the candidates stand on policy issues",
        "political action committees PACs": "groups that raise money from individuals and then distribute it in the form of contributions to candidates that the group supports. PACs must register with the FEC and report their donations and contributions to it. Individual contributions to a PAC are limited to $5,000 per year, and a PAC may give up to $5,000 to a candidate for each election",
        "political culture": "an overall set of values widely shared within a society",
        "political efficacy": "the belief that one's political participation really matters—that one's vote can actually make a difference",
        "political ideology": "a coherent set of beliefs about politics, public policy, and public purpose, which helps give meaning to political events",
        "political issue": "an issue that arises when people disagree about a problem and how to fix it",
        "political participation": "all the activities used by citizens to influence the selection of political leaders or the policies they pursue. The most common means of political participation in a democracy is voting; other means include protest and civil disobedience",
        "political party": "in the words of the economist Anthony Downs, a team of men and women seeking to control the governing apparatus by gaining office in a duly constituted election",
        "political questions": "a doctrine developed by the federal courts and used as a means to avoid deciding some cases, principally those involving conflicts between the president and Congress",
        "political socialization": "the process through which individuals in a society acquire political attitudes, views, and knowledge, based on input from family, schools, the media, and politics",
        "poll taxes": "small taxes levied on the right to vote. Poll taxes were used by most Southern states to exclude African Americans from voting",
        "pork barrel": "federal projects, grants, and contracts available to institutions in a congressional district, state and local governments, businesses, colleges, and other",
        "potential group": "all the people who might be interest group members because they share some common interest",
        "poverty line": "the income threshold below which people are considered poor, based on what a family must spend for an austere standard of living, traditionally set at three times the cost of a subsistence diet",
        "precedent": "how similar cases have been decided in the past",
        "presidential primaries": "elections in which a state's voters go to the polls to express their preference for a party's nominee for president. Most delegates to the national party conventions are chosen this way",
        "press conferences": "meetings of public officials with reporters",
        "print media": "newspapers and magazines, as compared with electronic media",
        "prior restraint": "government actions that prevent material from being published. As confirmed in Near v. Minnesota, prior restraint is usually prohibited by the First Amendment",
        "privileges and immunities": "the provision of the Constitution according citizens of each state the privileges of citizens of any state in which they happen to be",
        "probable cause": "reasonable grounds for believing that a person is guilty of a crime. In order to make a lawful arrest, the police must have probable cause",
        "progressive tax": "a tax by which the government takes a greater share of the income of the rich than of the poor—for example, when a rich family pays 50 percent of its income in taxes, and a poor family pays 5 percent",
        "project grants": "federal categorical grants given for specific purposes and awarded on the basis of the merits of applications",
        "proportional representation": "an electoral system used throughout most of Europe that awards legislative seats to political parties in proportion to the number of votes won in an election",
        "proportional tax": "a tax by which the government takes the same share of income from everyone, rich and poor alike",
        "protest": "a form of political participation designed to achieve policy change through dramatic and unconventional tactics",
        "public interest lobbies": "organizations that seek a collective good, which benefits the society as a whole",
        "public opinion": "the distribution of the population's beliefs about politics and policy issues",
        "public policy": "a choice that government makes in response to a political issue. A policy is a course of action taken with regard to some problem",
        "random-digit dialing": "a technique used by pollsters to place telephone calls randomly to both listed and unlisted numbers when conducting a survey",
        "random sampling": "the key technique employed by survey researchers, which operates on the principle that everyone should have an equal probability of being selected for the sample",
        "rational-choice theory": "a popular theory in political science to explain the actions of voters as well as politicians. It assumes that individuals act in their own best interest, carefully weighing the costs and benefits of possible alternatives",
        "reapportionment": "the process of reallocating seats in the House of Representatives every 10 years on the basis of the results of the Census",
        "reconciliation": "a congressional process through which program authorizations are revised to achieve required savings. It usually also includes tax or other revenue adjustments",
        "Red Lion Broadcasting Company v. Federal Communications Commission": "a 1969 case in which the Supreme Court upheld restrictions on radio and television broadcasting similar to those it had overturned in Miami Herald Publishing Company v. Tornillo. The Court reasoned that regulating radio and television broadcasting is justified because there are only a limited number of broadcasting frequencies available",
        "Reed v. Reed": "the landmark case in 1971 in which the Supreme Court for the first time upheld a claim of gender discrimination",
        "Regents of the University of California v. Bakke": "a 1978 Supreme Court decision holding that a state university may weigh race or ethnic background as one element in admissions but may not set aside places for members of particular racial groups",
        "regressive tax": "a tax in which the burden falls relatively more heavily on low-income groups than on wealthy taxpayers. The opposite of a progressive tax, in which tax rates increase as income increases",
        "regulation": "the use of governmental authority to control or change some practice in the private sector",
        "relative deprivation": "a perception by an individual that he or she is not doing well economically in comparison to others",
        "representation": "a basic principle of traditional democratic theory that describes the relationship between the few leaders and the many followers",
        "republic": "a form of government in which the people select representatives to govern them and make laws",
        "responsible party model": "a view about how parties should work, held by some political scientists. According to the model, parties should offer clear choices to the voters and once in office, should carry out their campaign promises",
        "revenues": "the financial resources of the government. The individual income tax and Social Security tax are major sources of the federal government's revenue",
        "right to privacy": "the right to a private personal life free from the intrusion of government",
        "right-to-work laws": "state laws that forbid the creation of union shops. These laws were specifically authorized by the Taft-Hartley Act of 1947",
        "Roe v. Wade": "the 1973 Supreme Court decision holding that a Texas state ban on abortions was unconstitutional. The decision forbade state control over abortions during the first trimester of pregnancy, permitted states to limit abortions to protect a mother's health in the second trimester, and permitted states to ban abortion during the third trimester",
        "Roth v. United States": "a 1957 Supreme Court decision ruling that obscenity is not within the area of constitutionally protected speech or press",
        "sample": "a relatively small proportion of people who are chosen in a survey so as to be representative of the whole",
        "sampling error": "the level of confidence in the findings of a public opinion poll. The more people interviewed, the more confident one can be of the results",
        "Schenck v. United States": "a 1919 Supreme Court decision upholding the conviction of a socialist who had urged resistance to the draft during World War I. Justice Holmes declared that government can limit speech if the speech provokes a clear and present danger of substantive evils",
        "School District of Abington Township, Pennsylvania v. Schempp": "the 1963 Supreme Court decision holding that a Pennsylvania law requiring Bible reading in schools violated the establishment clause of the First Amendment",
        "Scott v. Sandford": "the 1857 Supreme Court decision ruling that a slave who had escaped to a free state enjoyed no rights as a citizen and that Congress had no authority to ban slavery in the territories",
        "search warrant": "a written authorization from a court specifying the area to be searched and what the police may search for",
        "selective benefits": "goods that a group can restrict to those who actually join",
        "selective exposure": "the process through which people consciously choose to get the news from information sources that have viewpoints compatible with their own",
        "selective perception": "the phenomenon that people's beliefs often guide what they pay the most attention to and how they interpret events",
        "self-incrimination": "being a witness against oneself. The Fifth Amendment forbids involuntary self-incrimination",
        "Senate Finance Committee": "the Senate committee that, along with the House Ways and Means Committee, writes the tax codes, subject to the approval of Congress as a whole",
        "senatorial courtesy": "an unwritten tradition whereby nominations for state-level federal judicial posts are usually not confirmed if they are opposed by a senator of the president's party from the state in which the nominee will serve. The tradition also applies to courts of appeals when there is opposition from a senator of the president's party who is from the nominee's state",
        "Senior Executive Service": "an elite cadre of about 9,000 federal government managers at the top of the civil service system",
        "seniority system": "a simple rule for picking committee chairs, in effect until the 1970s. The member who had served on the committee the longest and whose party controlled the chamber became chair, regardless of party loyalty, mental state, or competence",
        "separation of powers": "a feature of the Constitution that requires the three branches of government—executive, legislative, and judicial—to be relatively independent of each other so that one cannot control the others. Power is shared among these three institutions",
        "Shays's Rebellion": "a series of attacks on courthouses by a small band of farmers led by Revolutionary War captain Daniel Shays to block foreclosure proceedings",
        "single-issue groups": "groups that have a narrow interest on which their members tend to take an uncompromising stance",
        "Sixteenth Amendment": "the constitutional amendment adopted in 1913 that explicitly permitted Congress to levy an income tax",
        "Sixth Amendment": "a constitutional amendment designed to protect individuals accused of crimes. It includes the right to counsel, the right to confront witnesses, and the right to a speedy and public trial",
        "Social Security Act": "a 1935 law intended to provide a minimal level of sustenance to older Americans and thus save them from poverty",
        "Social Security Trust Fund": "the account into which Social Security employee and employer contributions are deposited and used to pay out eligible recipients",
        "social welfare policies": "policies that provide benefits, cash or in-kind, to individuals, based on either entitlement or means testing",
        "soft money": "political contributions earmarked for party-building expenses at the grassroots level or for generic party advertising. For a time, such contributions were unlimited, until they were banned by the McCain-Feingold Act",
        "solicitor general": "a presidential appointee and the third-ranking office in the Department of Justice. The solicitor general is in charge of the appellate court litigation of the federal government",
        "sound bites": "short video clips of approximately 10 seconds. Typically, they are all that is shown from a politician's speech on the nightly television news",
        "Speaker of the House": "an office mandated by the Constitution. The Speaker is chosen in practice by the majority party, has both formal and informal powers, and is second in line after the Vice President to succeed to the presidency should that office become vacant",
        "standard operating procedures": "better known as SOPs, these procedures for everyday decision making enable bureaucrats to bring efficiency and uniformity to the running of complex organizations. Uniformity promotes fairness and makes personnel interchangeable",
        "standing committees": "committees in each house of Congress that handle bills in different policy areas",
        "standing to sue": "the requirement that plaintiffs have a serious interest in a case, which depends on whether they have sustained or are likely to sustain a direct and substantial injury from another party or from an action of government",
        "stare decisis": "a Latin phrase meaning let the decision stand. Most cases reaching appellate courts are settled on this principle",
        "statutory construction": "the judicial interpretation of an act of Congress. In some cases where statutory construction is an issue, Congress passes new legislation to clarify existing laws",
        "street-level bureaucrats": "a phrase referring to those bureaucrats who are in constant contact with the public and have considerable administrative discretion",
        "suffrage": "the legal right to vote, extended to African Americans by the Fifteenth Amendment, to women by the Nineteenth Amendment, and to 18- to 20-year-olds by the Twenty-sixth Amendment",
        "Super PACs": "independent expenditure-only PACs are known as Super PACs because they may accept donations of any size and can endorse candidates. Their contributions and expenditures must be periodically reported to the FEC",
        "superdelegates": "national party leaders who automatically get a delegate slot at the Democratic Party's national convention",
        "Superfund": "a fund created by Congress in 1980 to clean up hazardous waste sites",
        "supply-side economics": "an economic theory, first applied during the Reagan administration, holding that the key task for fiscal policy is to stimulate the supply of goods, as by cutting tax rates",
        "supremacy clause": "the clause in Article VI of the Constitution that makes the Constitution, national laws, and treaties supreme over state laws as long as the national government is acting within its constitutional limits",
        "Supreme Court": "the pinnacle of the American judicial system. The Court ensures uniformity in interpreting national laws, resolves conflicts among states, and maintains national supremacy in law. It has both original jurisdiction and appellate jurisdiction",
        "symbolic speech": "nonverbal communication, such as burning a flag or wearing an armband. The Supreme Court has accorded some symbolic speech protection under the First Amendment",
        "talking head": "a shot of a person's face talking directly to the camera. Because such shots are visually unstimulating, the major networks rarely show politicians talking for very long",
        "tax expenditures": "revenue losses that result from special exemptions, exclusions, or deductions allowed by federal tax law",
        "Temporary Assistance for Needy Families": "replacing Aid to Families with Dependent Children as the program for public assistance to needy families, TANF requires people on welfare to find work within two years and sets a lifetime maximum of five years",
        "Tenth Amendment": "the constitutional amendment stating, 'The powers not delegated to the United States by the Constitution, nor prohibited by it to the states, are reserved to the states respectively, or to the people'",
        "Texas v. Johnson": "a 1989 case in which the Supreme Court struck down a law banning the burning of the American flag on the grounds that such action was symbolic speech protected by the First Amendment",
        "third parties": "electoral contenders other than the two major parties. American third parties are not unusual, but they rarely win elections",
        "Thirteenth Amendment": "the constitutional amendment ratified after the Civil War that forbade slavery and involuntary servitude",
        "ticket splitting": "voting with one party for one office and with another party for other offices",
        "transfer payments": "benefits given by the government directly to individuals either cash transfers, such as Social Security payments, or in-kind transfers, such as food stamps and low-interest college loans",
        "trial balloons": "intentional news leaks for the purpose of assessing the political reaction",
        "Twenty-fifth Amendment": "ratified in 1967, this amendment permits the vice president to become acting president if the vice president and the president's cabinet determine that the president is disabled, and it outlines how a recuperated president can reclaim the job",
        "Twenty-second Amendment": "ratified in 1951, this amendment limits presidents to two terms of office",
        "U.S. Constitution": "the document written in 1787 and ratified in 1788 that sets forth the institutional structure of the U.S. government, the tasks these institutions perform, and the relationships among them. It replaced the Articles of Confederation",
        "uncontrollable expenditures": "expenditures that are determined by how many eligible beneficiaries there are for a program or by previous obligations of the government and that Congress therefore cannot easily control",
        "underemployment rate": "as measured by the Bureau of Labor Statistics, a statistic that includes (1) people who aren't working and are actively seeking a job, (2) those who would like to work but have given up looking, and (3) those who are working part-time because they cannot find a full-time position",
        "unemployment rate": "as measured by the Bureau of Labor Statistics, the proportion of the labor force actively seeking work but unable to find jobs",
        "union shop": "a provision found in some collective bargaining agreements requiring that all employees of a unionized business join the union within a short period of being hired, usually 30 days, and remain members as a condition of employment",
        "unitary government": "a central government that holds supreme power in a nation. Most national governments today are unitary governments",
        "unreasonable searches and seizures": "obtaining evidence in an unlawful manner, a practice prohibited by the Fourth Amendment. The police must have probable cause and/or a search warrant in order to make a legal and proper search for and seizure of incriminating evidence and seize such evidence",
        "veto": "the constitutional power of the president to send a bill back to Congress with reasons for rejecting it. A two-thirds vote in each house can override a veto",
        "Virginia Plan": "the proposal at the Constitutional Convention that called for representation of each state in Congress to be proportional to its population",
        "voter registration": "a system adopted by the states that requires voters to register prior to voting. Some states require citizens to register as much as 30 days in advance, whereas others permit Election Day registration",
        "Voting Rights Act of 1965": "a law designed to help end formal and informal barriers to African American suffrage. Under the law, hundreds of thousands of African Americans registered to vote, and the number of African American elected officials increased dramatically",
        "War Powers Resolution": "a law passed in 1973, in reaction to American fighting in Vietnam and Cambodia, that requires presidents to consult with Congress whenever possible prior to using military force and to withdraw forces after 60 days unless Congress declares war or grants an extension. However, presidents have viewed the resolution as unconstitutional",
        "Water Pollution Control Act of 1972": "a law intended to clean up the nation's rivers and lakes by enabling regulation of point sources of pollution",
        "Watergate": "the events and scandal surrounding a break-in at the Democratic National Committee headquarters in 1972 and the subsequent cover-up of White House involvement, leading to the eventual resignation of President Nixon under the threat of impeachment",
        "wealth": "the value of assets owned",
        "whips": "party leaders who work with the majority leader or minority leader to count votes beforehand and lean on waverers whose votes are crucial to the passage of a bill favored by the party",
        "white primary": "primary elections from which African Americans were excluded, an exclusion that, in the heavily Democratic South, deprived African Americans of a voice in the real contests. The Supreme Court declared white primaries unconstitutional in 1944",
        "winner-take-all system": "an electoral system in which legislative seats are awarded only to the candidates who come in first in their constituencies",
        "writ of habeas corpus": "a court order requiring authorities to explain to a judge what lawful reason they have for holding a prisoner in custody",
        "Zelman v. Simmons-Harris": "the 2002 Supreme Court decision that upheld a state program providing families with vouchers that could be used to pay for tuition at religious schools",
        "Zurcher v. Stanford Daily": "a 1978 Supreme Court decision holding that a search warrant could be applied to a newspaper without necessarily violating the First Amendment rights to freedom of the press",
        "501(c) groups": "Groups that are exempted from reporting their contributions and can receive unlimited contributions. Section 501c of the tax code specifies that such groups cannot spend more than half their funds on political activities",
        "527 groups": "Independent political groups that are not subject to contribution restrictions because they do not directly seek the election of particular candidates. Section 527 of the tax code specifies that contributions to such groups must be reported to the IRS",
        "actual group": "The people in the potential group who actually join",
        "Adarand Constructors v. Pena": "A 1995 Supreme Court decision holding that federal programs that classify people by race, even for an ostensibly benign purpose such as expanding opportunities for minorities, should be presumed to be unconstitutional",
        "administrative discretion": "The authority of administrative actors to select among various responses to a given problem. Discretion is greatest when routines, or standard operating procedures, do not fit a case",
        "affirmative action": "A policy designed to give special attention to or compensatory treatment for members of some previously disadvantaged group",
        "Americans with Disabilities Act of 1990": "A law passed in 1990 that requires employers and public facilities to make reasonable accommodations for people with disabilities and prohibits discrimination against these individuals in employment",
        "amicus curiae (friend of the court) briefs": "Legal briefs submitted by a friend of the court for the purpose of influencing a court's decision by raising additional points of view and presenting information not contained in the briefs of the formal parties",
        "Anti-Federalists": "Opponents of the U.S. Constitution at the time when the states were contemplating its adoption",
        "appellate jurisdiction": "The jurisdiction of courts that hear cases brought to them on appeal from lower courts. These courts do not review the factual record, only the legal issues involved",
        "appropriations bill": "An act of Congress that actually funds programs within limits established by authorization bills. Appropriations usually cover one year",
        "Articles of Confederation": "The first constitution of the United States, adopted by Congress in 1777 and ratified in 1781. The Articles established the Continental Congress as the national legislature, but left most authority with the state legislatures",
        "authorization bill": "An act of Congress that establishes, continues, or changes a discretionary government program or an entitlement. It specifies program goals and maximum expenditures for discretionary programs",
        "Barron v. Baltimore": "The 1833 Supreme Court decision holding that the Bill of Rights restrained only the national government, not the states or cities",
        "battleground states": "The key states that the presidential campaigns focus on because they are most likely to decide the outcome of the Electoral College vote",
        "beats": "Specific locations from which news frequently emanates, such as Congress or the White House. Most top reporters work a particular beat, thereby becoming specialists in what goes on at that location",
        "bicameral legislature": "A legislature divided into two houses. The U.S. Congress and all state legislatures except Nebraska's are bicameral",
        "bill": "A proposed law, drafted in legal language. Anyone can draft a bill, but only a member of the House of Representatives or the Senate can formally submit a bill for consideration",
        "Bill of Rights": "The first 10 amendments to the U.S. Constitution, which define such basic liberties as freedom of religion, speech, and the press, and they guarantee defendants' rights",
        "block grants": "Federal grants given more or less automatically to states or communities to support broad programs in areas such as community development and social services",
        "Brown v. Board of Education": "The 1954 Supreme Court decision holding that school segregation is inherently unconstitutional because it violates the Fourteenth Amendment's guarantee of equal protection. This case marked the end of legal segregation in the United States",
        "budget": "A policy document allocating burdens (taxes) and benefits (expenditures)",
        "budget resolution": "A resolution binding Congress to a total expenditure level, supposedly the bottom line of all federal spending for all programs",
        "bureaucracy": "According to Max Weber, a hierarchical authority structure that uses task specialization, operates on the merit principle, and behaves with impersonality",
        "cabinet": "A group of presidential advisers not mentioned in the Constitution, although every president has had one. Today the cabinet is composed of 14 secretaries, the attorney general, and others designated by the president",
        "campaign contributions": "Donations that are made directly to a candidate or a party and that must be reported to the FEC. As of 2016, individuals were allowed to donate up to $2,700 per election to a candidate and up to $33,400 to a political party",
        "campaign strategy": "The master game plan candidates lay out to guide their electoral campaigns",
        "casework": "Activities of members of Congress that help constituents as individuals, particularly by cutting through bureaucratic red tape to get people what they think they have a right to get",
        "categorical grants": "Federal grants that can be used only for specific purposes, or categories, of state and local spending. They come with strings attached, such as nondiscrimination provisions",
        "caucus": "A system for selecting convention delegates used in about a dozen states in which voters must attend an open meeting to express their presidential preference",
        "caucus (congressional)": "A group of members of Congress sharing some interest or characteristic. Many are composed of members from both parties and from both houses",
        "Census": "An actual enumeration of the population, which the Constitution requires that the government conduct every 10 years. The Census is a valuable tool for understanding demographic changes",
        "chains": "Groups of newspapers published by media conglomerates and today accounting for over four-fifths of the nation's daily newspaper circulation",
        "Checks and balances": "Features of the Constitution that require each branch of the federal government to obtain the consent of the others for its actions; they limit the power of each branch",
        "Citizens United v. Federal Election Commission": "A 2010 landmark Supreme Court case that ruled that individuals, corporations, and unions could donate unlimited amounts of money to groups that make independent political expenditures",
        "Civic duty": "The belief that in order to support democratic government, a citizen should vote",
        "Civil disobedience": "A form of political participation based on a conscious decision to break a law believed to be unjust and to suffer the consequences",
        "Civil liberties": "The constitutional and other legal protections against government actions; formally set down in the Bill of Rights",
        "Civil rights": "Policies designed to protect people against arbitrary or discriminatory treatment by government officials or individuals",
        "Civil Rights Act of 1964": "The law making racial discrimination in public accommodations illegal, forbade many forms of job discrimination, and strengthened voting rights",
        "Civil service": "A system of hiring and promotion based on the merit principle and the desire to create a nonpartisan government",
        "Class action suits": "Lawsuits in which a small number of people sue on behalf of all people in similar circumstances",
        "Clean Air Act of 1970": "The law aimed at combating air pollution, by charging the EPA with protecting and improving the quality of the nation's air",
        "Closed primaries": "Elections to select party nominees in which only people who have registered in advance with the party can vote for that party's candidates, encouraging greater party loyalty",
        "Coalition": "A group of individuals with a common interest on which every political party depends",
        "Coalition government": "When two or more parties join together to form a majority in a national legislature; common in multiparty systems of Europe",
        "Collective goods": "Goods and services, such as clean air and clean water, that by their nature cannot be denied to anyone",
        "Command-and-control policy": "The typical system of regulation whereby government tells business how to reach certain goals, checks that these commands are followed, and punishes offenders",
        "Commercial speech": "Communication in the form of advertising, which can be restricted more than many other types of speech",
        "Committee chairs": "The most important influencers of their committees' agendas; play dominant roles in scheduling hearings, hiring staff, appointing subcommittees, and managing committee bills",
        "Conference committees": "Congressional committees formed when the Senate and the House pass a particular bill in different forms; Party leadership appoints members from each house to iron out differences and bring back a single bill",
        "Congressional Budget Office": "Advises Congress on the probable consequences of its decisions, forecasts revenues, and is a counterweight to the president's Office of Management and Budget",
        "Connecticut Compromise": "The compromise reached at the Constitutional Convention establishing two houses of Congress: the House of Representatives based on population and the Senate representing each state equally",
        "Consent of the governed": "The idea that government derives its authority from the people",
        "Constitution": "A nation's basic law; creates political institutions, assigns or divides powers in government, and often provides certain guarantees to citizens; can be written or unwritten",
        "Consumer price index": "The key measure of inflation—the change in the cost of buying a fixed basket of goods and services",
        "Continuing resolutions": "Resolutions allowing agencies to spend at the level of the previous year when Congress cannot pass appropriations bills",
        "Cooperative federalism": "A system of government in which states and the national government share powers and policy assignments",
        "Council of Economic Advisers": "A three-member body appointed by the president to advise the president on economic policy",
        "Courts of appeals": "Appellate courts empowered to review all final decisions of district courts, and also hear appeals to orders of many federal regulatory agencies",
        "Craig v. Boren": "The 1976 ruling in which the Supreme Court established the intermediate scrutiny standard for determining gender discrimination",
        "Crisis": "A sudden, unpredictable, and potentially dangerous event requiring the president to play the role of crisis manager",
        "Critical election": "An electoral earthquake where new issues emerge, new coalitions replace old ones, and the majority party is often displaced by the minority party",
        "Cruel and unusual punishment": "Court sentences prohibited by the Eighth Amendment",
        "Declaration of Independence": "The document approved by representatives of the American colonies in 1776 that stated their independence and grievances against the British monarch",
        "Deficit": "An excess of federal expenditures over federal revenues",
        "Democracy": "A system of selecting policymakers and organizing government so that policy represents and responds to the public's preferences",
        "Demography": "The science of population changes",
        "Deregulation": "The lifting of government restrictions on business, industry, and professional activities",
        "Devolution": "Transferring responsibility for policies from the federal government to state and local governments",
        "Carson Cousins": "The Genius, Billionaire, Playboy, Philanthropist who made this project",
        "Direct mail": "A method of raising money for a political cause or candidate, sending information and requests for money to people who have supported similar views or candidates in the past",
        "District courts": "The 91 federal courts of original jurisdiction, where trials are held and juries may be impaneled",
        "Dual federalism": "A system of government in which states and the national government each remain supreme within their own spheres, with different powers and policy responsibilities",
        "Due process clause": "Part of the Fourteenth Amendment guaranteeing that persons cannot be deprived of life, liberty, or property by the U.S. or state governments without due process of law",
        "Earned Income Tax Credit": "Also known as the EITC, a refundable federal income tax credit for low- to moderate-income working individuals and families",
        "Eighth Amendment": "The constitutional amendment that forbids cruel and unusual punishment",
        "Elastic clause": "The final paragraph of Article I, Section 8 of the Constitution authorizing Congress to pass all laws necessary and proper to carry out enumerated powers",
        "Electioneering": "Direct group involvement in the electoral process, helping fund campaigns, getting members to work for candidates, and forming political action committees",
        "Electoral College": "A unique American institution created by the Constitution, selecting the president by electors chosen by the popular vote in each state",
        "Electronic media": "Television, radio, and the Internet, as compared with print media",
        "Elitism": "A theory of American democracy contending that an upper-class elite holds the power and makes policy, regardless of formal government organization",
        "Endangered Species Act of 1973": "A law requiring the federal government to protect all species listed as endangered",
        "Engel v. Vitale": "The 1962 Supreme Court decision holding that state officials violated the First Amendment when they required public schoolchildren to recite a prayer",
        "Entitlement programs": "Government programs providing benefits to qualified individuals regardless of need",
        "Entitlements": "Policies for which Congress has obligated itself to pay X level of benefits to Y number of recipients, e.g., Social Security benefits",
        "Enumerated powers": "Powers of the federal government explicitly listed in the Constitution, such as Article I, Section 8",
        "Environmental impact statement": "A detailing of a proposed policy's environmental effects, required to be filed with the EPA for potentially disruptive policies",
        "Environmental Protection Agency": "The largest federal independent regulatory agency, created in 1970 to administer U.S. environmental protection policy",
        "Equal protection of the laws": "Part of the Fourteenth Amendment emphasizing that the laws must provide equivalent protection to all people",
        "Equal Rights Amendment (ERA)": "A constitutional amendment passed in 1972 stating that equality of rights under the law shall not be denied or abridged by the United States or any state on account of sex",
        "Establishment clause": "Part of the First Amendment stating that Congress shall make no law respecting an establishment of religion",
        "Exclusionary rule": "The rule that evidence cannot be introduced into a trial if it was not obtained in a constitutional manner; prohibits evidence from unreasonable search and seizure",
        "Executive orders": "Regulations originating with the executive branch; a method presidents can use to control the bureaucracy",
        "Exit poll": "Public opinion surveys used by major media pollsters to predict electoral winners quickly and accurately",
        "Expenditures": "Government spending; major areas include social services and national defense",
        "Extradition": "A legal process whereby a state surrenders a person charged with a crime to the state where the crime was allegedly committed",
        "Factions": "Groups such as interest groups that arise from unequal distribution of property or wealth and can cause instability in government",
        "Federal Election Campaign Act": "A 1974 law reforming campaign finances, creating the Federal Election Commission, and setting limits and disclosure requirements for campaign contributions",
        "Federal Election Commission": "A six-member bipartisan agency created to administer and enforce campaign finance laws",
        "Federal Reserve System": "The main instrument for making monetary policy in the U.S., created in 1913 to regulate bank lending practices and the money supply",
        "Federalism": "A way of organizing a nation so that two or more levels of government share formal authority over the same area and people",
        "Federalist Papers": "A set of 85 essays advocating ratification of the Constitution and providing commentary on the new system of government",
        "Federalists": "Supporters of the U.S. Constitution at the time the states were contemplating its adoption",
        "Feminization of poverty": "The increasing concentration of poverty among women, especially unmarried women and their children",
        "Fifteenth Amendment": "The constitutional amendment adopted in 1870 to extend suffrage to African Americans",
        "Fifth Amendment": "A constitutional amendment protecting persons accused of crimes; forbids double jeopardy, self-incrimination, and punishment without due process",
        "Filibuster": "A Senate strategy using unlimited debate to prevent a vote on legislation; 60 members present and voting can end a filibuster",
        "First Amendment": "The constitutional amendment protecting freedom of religion, speech, press, and assembly",
        "Fiscal federalism": "The pattern of spending, taxing, and providing grants in the federal system; cornerstone of federal-state relations",
        "Fiscal policy": "Use of the federal budget—taxes, spending, and borrowing—to influence the economy; almost entirely determined by Congress and the president",
        "Formula grants": "Federal categorical grants distributed according to a formula specified in legislation or administrative regulations",
        "Fourteenth Amendment": "Constitutional amendment stating no state shall abridge privileges or immunities of citizens, deprive life, liberty, or property without due process, or deny equal protection of the laws",
        "Free exercise clause": "A First Amendment provision prohibiting government interference with the practice of religion",
        "Free-rider problem": "For an interest group, the phenomenon where some potential members do not join because they can benefit without participating",
        "Frontloading": "The recent tendency of states to hold primaries early in the calendar to capitalize on media attention",
        "Full faith and credit": "A clause in Article IV of the Constitution requiring each state to recognize the public acts, records, and judicial proceedings of all other states",
        "Limited government": "a government's power cannot be absolute; The ideal of limited government is ensured by the interaction of these principles: i. Separation of powers ii. Checks and balances iii. Federalism iv. Republicanism",
        "Natural rights": "all people have certain rights that cannot be taken away",
        "Popular sovereignty": "all government power comes from the consent of its people",
        "Republicanism": "the democratic principle that the will of the people is reflected in government debates and decisions by their representatives",
        "Social contract": "an implicit agreement among the people in a society to give up some freedoms to maintain social order",
        "Representative democracy": "a system of government in which all eligible citizens vote on representatives to make public policy for them; can take several forms including the following models: i. Participatory democracy, ii. Pluralist democracy, iii. Elite democracy",
        "Participatory democracy": "emphasizes broad participation in politics and civil society",
        "Pluralist democracy": "emphasizes group-based activism by nongovernmental interests striving for impact on political decision making",
        "Elite democracy": "emphasizes limited participation in politics and civil society",
        "Declaration of Independence": "drafted by Thomas Jefferson (with help from Adams and Franklin), restates the philosophy of natural rights, and provides a foundation for popular sovereignty",
        "U.S. Constitution": "an example of a social contract and establishes a system of limited government; provides the blueprint for a unique form of democratic government in the United States",
        "Federalist 10": "focused on the superiority of a large republic in controlling the mischiefs of faction, delegating authority to elected representatives and dispersing power between the states and national government",
        "Brutus 1": "adhered to popular democratic theory that emphasized the benefits of a small, decentralized republic while warning of the dangers to personal liberty from a large, centralized government",
        "Articles of Confederation": "Specific incidents and legal challenges that highlighted key weaknesses of the Articles of Confederation are represented by the: i. Lack of centralized military power to address Shays' Rebellion ii. Lack of an executive branch to enforce laws, including taxation iii. Lack of a national court system iv. Lack of power to regulate interstate commerce v. Lack of power to coin money",
        "Anti-Federalist": "opposed the ratification of the Constitution and wanted more power reserved to state governments rather than a strong central government",
        "Federalist": "supported ratification of the Constitution and a strong central government",
        "Democracy": "a system of government in which power is vested in the people and exercised by them directly or through freely elected representatives",
        "Faction": "a party or group that is often contentious or self-seeking",
        "Shays's Rebellion": "an armed uprising in western Massachusetts in opposition to high taxation and insufficient economic policies that exposed concern over the weaknesses of the national government under the Articles of Confederation",
        "Great (Connecticut) Compromise": "created a dual (bicameral) system of congressional representation with the House of Representatives based on each state's population and the Senate representing each state equally",
        "Electoral College": "created a system for electing the president by electors from each state rather than by popular vote or by congressional vote",
        "3/5ths Compromise": "provided a formula for calculating a state's enslaved population for purposes of representation in the House and for taxation",
        "Constitutional Convention": "a meeting of delegates from the several states in 1787 intended to revise the Articles of Confederation and ultimately drafted the United States Constitution in establishing a stronger central government",
        "Article V / Amendment process": "entailed either a two-thirds vote in both houses or a proposal from two-thirds of the state legislatures, with final ratification determined by three-fourths of the states",
        "Ratification": "the act of consenting to the U.S. Constitution through state ratification conventions, requiring 9 of the 13 states to ratify per Article VII of the U.S. Constitution",
        "Separation of powers": "specific and separate powers delegated to Congress, the president, and the courts allow each branch to check and balance the power of the other branches, ensuring no one branch becomes too powerful; creates multiple access points for stakeholders and institutions to influence public policy",
        "Checks and balances": "allow legal actions to be taken against public officials deemed to have abused their power",
        "Federalist 51": "explains how constitutional provisions of separation of powers and checks and balances control potential abuses by majorities",
        "Impeachment": "the House formally charges an official with abuse of power or misconduct",
        "Removal (impeachment process)": "if the official is convicted in a Senate impeachment trial",
        "Federalism": "the system of government in the United States in which power is shared between the national and state governments",
        "Enumerated powers": "written in the Constitution",
        "Implied powers": "not specifically written in the Constitution but are inferred from the Necessary and Proper Clause",
        "Reserved powers": "those not delegated or enumerated to the national government but are reserved to the states, as stated in the Tenth Amendment",
        "Concurrent powers": "shared between both levels of government such as the power to collect taxes, the power to make and enforce laws and the power to build roads",
        "Revenue sharing": "national funding with almost no restrictions to the states on its use and is the least used form of funding",
        "Categorical grants": "national funding that is restricted to specific categories of expenditures, is preferred by the national government, and is the most commonly used form of funding",
        "Block grants": "national funding with minimal restrictions to the states on its use and is preferred by the states",
        "Mandates": "requirements by the national government of the states",
        "Tenth Amendment": "the last of the Bill of Rights to define the balance of power between the federal government and the states; establishes reserved powers of the states",
        "Fourteenth Amendment": "Due Process Clause and Equal Protection Clause as applied to the states",
        "Commerce clause": "gives the national government the power to regulate interstate commerce, but Supreme Court interpretations can influence the extent of this power",
        "Necessary and Proper clause / Elastic clause": "gives Congress the power to make laws related to carrying out its enumerated powers, but Supreme Court interpretations can influence the extent of these powers",
        "Supremacy Clause": "gives the national government and its laws general precedence over states' laws, but Supreme Court interpretations may affect when specific actions exceed this constitutional power"
    }



    lowercase_glossary = {k.lower(): v for k, v in glossary_dict.items()}


    word = input("Enter vocab word: ").strip().lower()
    definition = lowercase_glossary.get(word)
    
    if definition:
        print(f"Definition of '{word}':\n{definition}")
    else:
        print(f"Sorry, the word '{word}' was not found in the glossary.")
    
    more = input("Are you still going? (say 'no' to go back to the menu, otherwise just press enter.) ").strip().lower()
    if more != "no":
        get_definition()
    else:
        menu()
                 
def quiz():
    os.system('cls' if os.name == 'nt' else 'clear')
    word, definition = random.choice(list(chap_vocab.items()))
    print("Word:", word)
    ready = input("Press enter to see the definition.")
    print("Definition:", definition)
    continu = input("keep practicing? (say 'no' to go back to the menu, otherwise just press enter.) ")
    if continu != "no":
        quiz()
    else:
        menu()

def chapone():
    global chap_vocab
    chap_vocab = {
    "Single Issue Group": "Groups that have a narrow interest on which their members tend to take an uncompromising stance",
    "Linkage Institutions": "The political channels through which peoples concerns become political issues on the policy agenda. In the United States, linkage institutions include elections, political parties, interest groups, and the media",
    "Policy Agenda": "The issues that attract serious attention of public officials and other people involved in politics at a point in time.",
    "Public Policy": "A choice that government makes in response to a political issue. A policy is a course of action taken with regard to some problem.",
    "Democracy": "A system of selecting policymakers and of organizing governments so that policy represents and responds to the publics preferences.",
    "Majority Rule": "A fundamental principle of traditional democratic theory. In a democracy, choosing among alternatives requires that the majoritys desire must be respected",
    "Minority Rights": "A principle of traditional democratic theory that guarantees rights to those who do not belong to majorities",
    "Policy Gridlock": "A condition that occurs when interests conflict and no coalition is strong enough to form a majority and establish policy, so nothing gets done.",
    "Republicanism": "The democratic principle that the will of the people is reflected in government debates and decisions by their representatives",
    "Popular Sovereignty": "All government power comes from the consent of the people",
    "Judicial Review": "The power of the courts to determine whether the acts of the courts and those of the executive branch are in accord with the US constitution. Judicial review was established by marbury v madison",
    "Separation of Powers": "Specific and separate powers delegated to Congress, the president, and the courts allow each branch to check and balance the power of the other branches, ensuring no one branch becomes too powerful; creates multiple access points for stakeholders and institutions to influence public policy",
    "Participatory Democracy": "Emphasizes broad participation in politics and civil society",
    "Pluralist Democracy": "Emphasizes group-based activism by non governmental interests striving for impact on political decision making",
    "Elite Democracy": "Emphasizes limited participation in politics and civil society",
    "Hyperpluralism": "A theory of american democracy arguing that a wide variety of interest groups have become empowered with the ability to veto policy change leading to a regular gridlock in washington",
    "Limited Government": "A governments power cannot be absolute; The ideal of limited government is ensured by the interaction of these principles: i. Separation of powers ii. Checks and balances iii. Federalism iv. Republicanism",
    "Natural Rights": "All people have certain rights that cannot be taken away",
    "Social Contract": "An implicit agreement among the people in society to give up some freedoms to maintain social order.",
    "Representative Democracy": "A system of government in which all eligible citizens to vote on representatives to make public policy for them; can take several forms including the following models: i. Participatory democracy, ii. Pluralist democracy, iii. Elite democracy"
}
    
    
def chaptwo():
    global chap_vocab
    chap_vocab = {
    "Declaration of Independence": "The document approved by representatives of the American colonies in 1776 that stated their grievances against the British monarch and declared their independence.",
    "Natural rights": "Rights inherent in human beings, not dependent on governments, which include life, liberty, and property. The concept of natural rights was central to English philosopher John Locke's theories about government and was widely accepted among America's Founders.",
    "Consent of the governed": "The idea that government derives its authority from the people.",
    "Limited government": "The idea that certain restrictions should be placed on government to protect the natural rights of citizens.",
    "Articles of Confederation": "The first constitution of the United States, adopted by Congress in 1777 and ratified in 1781. The Articles established the Continental Congress as the national legislature, but left most authority with the state legislatures.",
    "Shay’s Rebellion": "A series of attacks on courthouses by a small band of farmers led by Revolutionary War captain Daniel Shays to block foreclosure proceedings.",
    "U.S. Constitution": "The document written in 1787 and ratified in 1788 that sets forth the institutional structure of the U.S. government, the tasks these institutions perform, and the relationships among them. It replaced the Articles of Confederation.",
    "Faction": "Groups such as interest groups that, according to James Madison, arise from the unequal distribution of property or wealth and have the potential to cause instability in government.",
    "New Jersey Plan": "The proposal at the Constitutional Convention that called for equal representation of each state in Congress regardless of the size of the state's population.",
    "Virginia Plan": "The proposal at the Constitutional Convention that called for representation of each state in Congress to be proportional to its population.",
    "Great (Connecticut) Compromise": "The compromise reached at the Constitutional Convention that established two houses of Congress: the House of Representatives, in which representation is based on a state's population; and the Senate, in which each state has two representatives.",
    "Writ of habeas corpus": "A court order requiring authorities to explain to a judge what lawful reason they have for holding a prisoner in custody.",
    "Separation of powers": "A feature of the Constitution that requires the three branches of government—executive, legislative, and judicial—to be relatively independent of each other so that one cannot control the others. Power is shared among these three institutions.",
    "Checks and balances": "Features of the Constitution that require each branch of the federal government to obtain the consent of the others for its actions; they limit the power of each branch.",
    "Federalists": "Supporters of the U.S. Constitution at the time the States were contemplating its adoption.",
    "Anti-Federalist": "Opponents of the U.S. Constitution at the time when the states were contemplating its adoption.",
    "Federalist Papers": "The Federalist Papers are a set of 85 essays that advocate ratification of the Constitution and provide insightful commentary on the nature of the new system of government.",
    "Bill of Rights": "The first 10 amendments to the U.S. Constitution, which define such basic liberties as freedom of religion, speech, and the press, and they guarantee defendants' rights.",
    "Equal Rights Amendment": "A constitutional amendment passed by Congress in 1972 stating that equality of rights under the law shall not be denied or abridged by the United States or by any state on account of sex. The amendment failed to acquire the necessary support from three-fourths of the state legislatures.",
    "Marbury v. Madison": "The 1803 case in which the Supreme Court asserted its power to determine the meaning of the U.S. Constitution. The decision established the Court's power of judicial review over acts of Congress.",
    "John Locke": "An English philosopher whose ideas about natural rights (life, liberty, and property) and the social contract heavily influenced the American Founders in creating a government that derives its power from the consent of the governed.",
    "3/5s Compromise": "Provided a formula for calculating a state's enslaved population for purposes of representation.",
    "Brutus No. 1": "Adhered to popular democratic theory that emphasized the benefits of a small, decentralized republic while warning of the dangers to personal liberty from a large, centralized government.",
    "Federalist 10": "Focused on the superiority of a large republic in controlling the mischiefs of faction, delegating authority to elected representatives and dispersing power between the states and national government.",
    "Ex post facto": "A law that makes an act a crime after it was committed or increases the penalties for a crime after it was committed; the Constitution prohibits Congress and the states from passing such laws.",
    "Selective incorporation": "A constitutional doctrine through which most protections in the Bill of Rights are applied to the states using the Fourteenth Amendment’s Due Process Clause.",
    "Bicameral legislature": "A legislature divided into two houses. The U.S. Congress and all state legislatures except Nebraska’s are bicameral.",
    "Ratification": "The act of consenting to the U.S. Constitution through state ratification conventions, requiring 9 of the 13 states to ratify per Article VII of the U.S. Constitution.",
    "Amendments": "Formal changes or additions to the Constitution that alter its language or meaning; the first ten are the Bill of Rights.",
    "Delegated/expressed/enumerated powers": "Powers explicitly granted to the federal government by the Constitution, often listed in Article I, Section 8, such as the power to tax, coin money, and regulate commerce.",
    "Reserved powers": "Those not delegated or enumerated to the national government but are reserved to the states, as stated in the Tenth Amendment.",
    "Concurrent powers": "Shared between both levels of government such as the power to collect taxes, the power to make and enforce laws and the power to build roads.",
    "Implied powers": "Powers of the federal government that go beyond those enumerated in the Constitution, in accordance with the statement in the Constitution that Congress has the power to make all laws necessary and proper for carrying into execution the powers enumerated in Article I.",
    "Electoral College": "A unique American institution created by the Constitution, providing for the selection of the president by electors chosen by the popular vote within each state. Throughout American history, the winner of the Electoral College vote has usually been the candidate who has won the popular vote. However, in 2000 President George W. Bush was elected even though Al Gore won the popular vote, and President Trump was elected in 2016 even though Hillary Clinton won more votes nationwide.",
    "Constitutional Convention": "A meeting of delegates from the several states in 1787 intended to revise the Articles of Convention and ultimately drafted the United States Constitution in establishing a stronger central government.",
    "Federalist 51": "Explains how constitutional provisions of separation of powers and checks and balances control potential abuses by majorities.",
    "Impeachment": "The political equivalent of an indictment in criminal law, prescribed by the Constitution. The House of Representatives may impeach the president by a majority vote for Treason, Bribery, or other high Crimes and Misdemeanors.",
    "Removal (impeachment process)": "If the official is convicted in a Senate impeachment trial."
}

def chapthree():
    global chap_vocab
    chap_vocab = {
    "block grants": "national funding with minimal restrictions to the states on its use and is preferred by the states",
    "categorical grants": "Federal categorical grants distributed according to a formula specified in legislation or administrative regulations",
    "concurrent powers": "shared between both levels of government such as the power to collect taxes, the power to make and enforce laws and the power to build roads",
    "denied power": "A power that the Constitution explicitly prohibits the national government, state governments, or both from exercising.",
    "devolution": "Transferring responsibility for policies from the federal government to state and local governments",
    "enumerated powers/delegated": "written in the Constitution",
    "Federalism": "the system of government in the United States in which power is shared between the national and state governments",
    "Federalist 51": "explains how constitutional provisions of separation of powers and checks and balances control potential abuses by majorities",
    "fiscal federalism": "The pattern of spending, taxing, and providing grants in the federal system; cornerstone of federal-state relations",
    "Formula grants": "Federal categorical grants distributed according to a formula specified in legislation or administrative regulations",
    "Fourteenth Amendment": "Due Process Clause and Equal Protection Clause as applied to the states",
    "full faith and credit clause": "A clause in Article IV of the Constitution requiring each state to recognize the public acts, records, and judicial proceedings of all other states",
    "Grants-in-aid": "Federal funds provided to state and local governments for specific purposes, often with conditions attached.",
    "implied powers": "not specifically written in the Constitution but are inferred from the Necessary and Proper Clause",
    "inherent powers": "Powers that are not explicitly stated in the Constitution but are naturally held by any national government as part of its sovereignty.",
    "McCulloch v.Maryland": "an 1819 Supreme Court decision that established the supremacy of the national government over state governments. The Court, led by Chief Justice John Marshall, held that Congress had certain implied powers in addition to the powers enumerated in the Constitution",
    "Necessary and proper/elastic clause": "gives Congress the power to make laws related to carrying out its enumerated powers, but Supreme Court interpretations can influence the extent of these powers",
    "privileges and immunities clause": "the provision of the Constitution according citizens of each state the privileges of citizens of any state in which they happen to be",
    "project grants": "federal categorical grants given for specific purposes and awarded on the basis of the merits of applications",
    "reserved powers": "those not delegated or enumerated to the national government but are reserved to the states, as stated in the Tenth Amendment",
    "revenue sharing": "national funding with almost no restrictions to the states on its use and is the least used form of funding",
    "supremacy clause": "The clause in Article VI of the Constitution that makes the Constitution, national laws, and treaties supreme over state laws as long as the national government is acting within its constitutional limits",
    "Tenth Amendment": "The constitutional amendment stating, 'The powers not delegated to the United States by the Constitution, nor prohibited by it to the states, are reserved to the states respectively.'",
    "mandates": "requirements by the national government of the states",
    "Unfunded mandates": "Federal requirements that state or local governments must follow, but the national government provides little or no funding to cover the costs.",
    "US v Lopez": "A Supreme Court case that limited Congress’s power under the Commerce Clause."
}


def menu():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("This is a program that defines AP Government vocab terms and provides digital flashcards for each chapter.")
    function = input("what are we doing today gang? (flashcards) or (defining vocab terms) ")
    if function == ("defining vocab terms"):
        get_definition()
    elif function == ("flashcards"):
        unit = int(input("which chapter do you want to look at? (1, 2 or 3) "))
        if unit == 1:
            chapone()
            quiz()
        if unit == 2:
            chaptwo()
            quiz()
        if unit == 3:
            chapthree()
            quiz()
menu()


